### ISSUE TITLE
Latest solution won't build

### ISSUE THREAD

**Issue by toannguyen83** [JamieDixon/GraphViz-C-Sharp-Wrapper#5]
Hello, when I download the latest and run build.bat, it won't build.

I looked at the error and noticed some of the source files included unknown characters and thus won't compile.

For example in the Enum.cs
https://github.com/JamieDixon/GraphViz-C-Sharp-Wrapper/blob/master/src/GraphVizWrapper/Enums.cs

Notice that it has some weird characters inside
<<<<<<< HEAD
            Plain,
            PlainExt
=======
            Svg
>>>>>>> 41e86e4fab18dd87be9765e701865dc5d5ebe6c9

Another one in 
https://github.com/JamieDixon/GraphViz-C-Sharp-Wrapper/blob/master/src/GraphVizWrapper/GraphGeneration.cs
Line 156, same thing happened.

I suspected it comes from recent merge pull?

**Comment by JamieDixon** [comment]
Thanks @toannguyen83. It looks like there was a merge issue that I missed. I'll take a look at this when I get home.

**Comment by pbeza** [comment]
Same issue for me. I checked out HEAD^ and compilation is fine but unit tests fail ('Tests run: 4, Errors: 3').

**Comment by JamieDixon** [comment]
Hi guys. It looks like one of the build tasks was failing to do anything. It should have been copying the graphviz exes to the proper locations and the tests were failing because these files were missing. I've replaced these copy build steps with a simple unzip for now. If you have further problems building then please let me know. I've also removed the build step that compiled the sample project as this project no longer builds on my system (Windows 8.1 VS2013). I'll modernise the app at some point.

**Comment by toannguyen83** [comment]
Thanks @JamieDixon ! The build script is working now.
