### ISSUE TITLE
..\src\GraphViz.zip

### ISSUE THREAD

**Issue by Dimpl** [JamieDixon/GraphViz-C-Sharp-Wrapper#9]
The build file appears to be looking for GraphViz.zip in the src folder, but this file doesn't exist?

**Comment by Dimpl** [comment]
I downloaded GraphViz 2.38 from the website and the build progressed to unit tests, but these failed due to an invalid directory name.

**Comment by Dimpl** [comment]
I changed the location in app.config in the unit tests, the newest error is 'The system cannot find the file specified.'

**Comment by Dimpl** [comment]
And I changed the location again to \bin and I got a success!

**Comment by JamieDixon** [comment]
Thanks @Dimpl This is really helpful.

I removed the GraphViz.zip a while back because it was so huge. It was taking people a long time to clone the repo and it sort of tied them in to a version of GraphViz that happened to be here.

Your PR looks great. I'll aim to merge these changes in later on. I'm also considering creating a new config element for the parser location (dot.exe etc). It looks like these have been moved into the GraphViz `bin` folder as you've pointed out. Better to let users specify the location in config than having to modify the code depending on their GraphViz version.

Thanks again. It's really great when people take time out of their lives to help improve an OSS project. +1

**Comment by Dimpl** [comment]
Thanks for developing this in the first place, it's been really useful! I agree re the bin folder, as I am making a visualisation tool, and do not want each user to need to install graphviz to use it. I'll try to modify the 'Getting Started' to include graphviz installation.
